// <auto-generated />
using API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations.CurrencyQuotation
{
    [DbContext(typeof(CurrencyQuotationContext))]
    partial class CurrencyQuotationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Entities.CurrencyQuotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("timestamp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CurrencyQuotations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            destination = "ARS",
                            rate = 99.148817m,
                            source = "USD",
                            timestamp = 1634371754
                        },
                        new
                        {
                            Id = 2,
                            destination = "AED",
                            rate = 3.673104m,
                            source = "USD",
                            timestamp = 1634371754
                        },
                        new
                        {
                            Id = 3,
                            destination = "AFN",
                            rate = 89.350404m,
                            source = "USD",
                            timestamp = 1634371754
                        },
                        new
                        {
                            Id = 4,
                            destination = "ALL",
                            rate = 104.803989m,
                            source = "USD",
                            timestamp = 1634371754
                        },
                        new
                        {
                            Id = 5,
                            destination = "AMD",
                            rate = 478.420403m,
                            source = "USD",
                            timestamp = 1634371754
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
